### ISSUE TITLE
Fix to Makefile for board olimex_ice40hx8k_evb_ice40-io

### ISSUE THREAD

**Issue by mobluse** [alangarf/apple-one#16]
I had to fix the Makefile for board olimex_ice40hx8k_evb_ice40-io:
https://github.com/alangarf/apple-one/blob/master/boards/olimex_ice40hx8k_evb_ice40-io/yosys/Makefile

I had to change to this, i.e. go up one level higher:
`SOURCEDIR = ../../../rtl`

I can confirm I could upload the resulting apple1.bin using `winiceprogduino.exe -Icom5 apple1.bin` in Cmd.exe in Windows 10 and it works great! I compiled using WSL Ubuntu from Microsoft Store.

**Comment by alangarf** [comment]
Cheers, I'll have a look and push a fix. Thanks!

**Comment by alangarf** [comment]
Fixed in ddbbae966f271f4616b3ec33b2bc2ff2abac2a3b

Thanks again!
