### ISSUE TITLE
Modify to load as a MiSTer core?

### ISSUE THREAD

**Issue by JackZielke** [alangarf/apple-one#20]
Would anyone that has the knowhow be interested in converting this to be a core for [MiSTer](https://github.com/MiSTer-devel/Main_MiSTer/wiki)?  It runs on the DE10-Nano and provides HDMI output and USB keyboard input.  There is already an [Apple II+](https://github.com/MiSTer-devel/Apple-II_MiSTer) core.

**Comment by alangarf** [comment]
PRs happily accepted. 😃 

Shouldn't be too difficult, but I haven't got the time myself.

**Comment by alangarf** [comment]
Man, found on the Atari Forum someone has "merged" this core into their project and made a mess of the structure and dumped all the files into a random directory. :( Will make keeping that up to date hard.

**Comment by JackZielke** [comment]
Was it [this one](https://github.com/Gehstock/Mist_FPGA/tree/master/Apple%20-%201_MiST)?  That is for MiST, which is pretty close to MiSTer.  I am hoping this will make it even easier to port to MiSTer (I do not have a MiST FPGA).

On a related note, I have been converting cassette save files back to the original BASIC code [here](https://linuxcoffee.com/apple1/software/).  I was envisioning using the On Screen Display to load text files as if they were being typed on the keyboard.

**Comment by alanswx** [comment]
I started with the MiST version, so unfortunately the directories are all wrong:
https://github.com/MiSTer-devel/Apple-I_MiSTer

I added some code to load code from text files. It isn't fully working yet. I need to fix it.

**Comment by alangarf** [comment]
Hi,

I'd appreciate it if the MiST project could get the Apple One code back inline with this repo. Dumping all the RTL into a single directory is kinda poor and doesn't allow any modifications to trickle back to this project.

While I understand the excitement in adding it to MiST my work appears to have been misrepresented.

Thanks,
-A.

**Comment by alanswx** [comment]
Let me see if I can pull it back together to look more like yours. In general the code goes into https://github.com/miSTer-devel/ as it's own repo. There are very few (if any?) forks in the main repo. The naming convention of some of the directories are important for the scripts to auto upgrade cores from the RBF files.  Do you have a MiSTer yet? Are you interested in getting one?

**Comment by alanswx** [comment]
Take another look. https://github.com/MiSTer-devel/Apple-I_MiSTer

I can pull in the rest of your files. We can merge my changes back into your head, and then I can check out a fork of yours maybe? I think I just need the "releases" folder in the top level so the scripts will find it.

**Comment by alangarf** [comment]
Look good. Cheers.
