### ISSUE TITLE
Issue with PS/2 keyboard on Terasic DE0 Board

### ISSUE THREAD

**Issue by dennyalbert** [alangarf/apple-one#22]
When I flash the sof-file everything works correctly. But when I flash the pof-file to keep the software after a power cycle the keyboard doesn't work correctly anymore. The buttons are mixed-up completely. Any idea what goes wrong here and how to fix? I use the Quartus II 13.1 (32-bit) Web Edition.

**Comment by trcwm** [comment]
Hi @dennyalbert,

I haven't seen this issue before. My A1 boots correctly when I flash the configuration files.
Do you verify the flash contents after flashing? Could be your config flash is corrupt.
The other possibility it that Quartus does not produce the correct .pof file. 
Can you attach your .pof file?

/Niels.

**Comment by dennyalbert** [comment]
Hi @trcwm,

attached please find my pof-file.
Yes I did a verify and everything seems to be ok.
 
[apple-one.zip](https://github.com/alangarf/apple-one/files/1904476/apple-one.zip)

Regards,

Denny

**Comment by trcwm** [comment]
Your .pof file works perfectly on my DE0 system. I'm not sure how to help you further I'm afraid.

/Niels.

**Comment by dennyalbert** [comment]
I have now tested the workflow under windows without success. Only to rule out an error with the operating system. Otherwise I use linux.

Could I have a problem with the hardware?
I have tested some examples, everything has worked without any problems.
If there is a problem with the memory, should not the verify lead to an error?

Is there a possibility to read the memory bit-by-bit and compare that with the pof-file?

**Comment by dennyalbert** [comment]
Now I have read the configuration from the board and there are many differences between the two files. How can that happen, shouldn’t be the files identical?
Attached the two files.
[read&written.zip](https://github.com/alangarf/apple-one/files/1912964/read.written.zip)

**Comment by trcwm** [comment]
Have you erased the flash chip before programming?

**Comment by dennyalbert** [comment]
I had the opportunity to test on a second Terasic DE0 board and have the same issue.
I tried to establish a connection via the serial interface, unfortunately without success. Attached two screenshots. Do you have any idea why the connection does not work?
![reset](https://user-images.githubusercontent.com/37122033/39409854-4e01a8c0-4bee-11e8-9d92-87c69b786357.jpg)
![switch_off](https://user-images.githubusercontent.com/37122033/39409855-4e2039a2-4bee-11e8-9b2c-8375260889f5.jpg)

**Comment by trcwm** [comment]
Are you using a RS232 compliant serial to USB cable? A normal TTL-level cable won't work.

**Comment by trcwm** [comment]
Yes, the DE0 has a level translator (unlike many other boards) and it is directly compatible with an RS232 COM port.

I power cycle the DE0 when changing the position of the RUN/PROG switch. I have never seen it misbehave in either state. 

When I power up in the PROG state, the DE0 does nothing. When I power up in the RUN state (and the flash has been programmed), my A1 works as intended.

**Comment by dennyalbert** [comment]
This is really annoying that two boards behave differently.
Just to clarify, do I only need to load the pof-file or do I have to do some other configurations like for unused pins?

**Comment by trcwm** [comment]
To my knowledge there are no additional requirements to make the A1 run from config flash.
You board seems to work ok if the configuration was loaded directly from the PC. My best guess is that your config flash is not working properly.

**Comment by dennyalbert** [comment]
This was also my first guess that the config flash is the problem. But the same issue with two new boards? Unfortunately the EPCS4 is no longer available.

**Comment by dennyalbert** [comment]
Unfortunately I have the same problem with your files.

**Comment by dennyalbert** [comment]
Now I have built a cable for the serial port as described in the picture. I can receive characters but not send. Is there something special to do? Can the PS/2 keyboard stay connected?
![cable](https://user-images.githubusercontent.com/37122033/39602106-76e2de92-4f24-11e8-9e6d-669420d396d4.jpg)
![serial](https://user-images.githubusercontent.com/37122033/39602108-770c8cce-4f24-11e8-802e-9335c88eb4a5.jpg)

**Comment by trcwm** [comment]
If I'm not mistaken, the code will only transmit the data sent to the VGA to the UART.
The functionality to get the keyboard data from the UART is disabled by default.
You have to set the 'ps2_select' value in apple1_de0_top.v to zero.

**Comment by dennyalbert** [comment]
I'm getting closer to the problem. The keyboard (Fujitsu KB400) itself seems to be the problem.
If I supply the keyboard with voltage before the FPGA everything works.
The same effect occurs if I press and hold the reset button (Button 0) before switching on and release afterwards.
Any ideas how to fix the problem?

**Comment by dennyalbert** [comment]
Now I was able to test with an old AT keyboard (PS/2 adapter) and can confirm my guess that the Fujitsu keyboard was the problem.

**Comment by alangarf** [comment]
Glad you solved it! 👍 how annoying 😄
