### ISSUE TITLE
Backspace sends '(' instead of '_'

### ISSUE THREAD

**Issue by mobluse** [alangarf/apple-one#28]
Backspace sends '(' instead of '\_'. At least on my iCE40HX8K-EVB with iCE40-IO, see video https://youtu.be/2yIBnhapzEU . You can backspace by typing '_' using **Shift**+**-** on US keyboard.

**Comment by mobluse** [comment]
I did this just now, but it still types `(` instead of `_` when I press `BS`. Also `git pull` showed _Already up-to-date._

**Comment by trcwm** [comment]
Sorry, my mistake. Pushed to my local GIT instead of the public one. Try again now :)

**Comment by mobluse** [comment]
Yes, it works now.
