### ISSUE TITLE
Maybe error in Memory Map

### ISSUE THREAD

**Issue by mobluse** [alangarf/apple-one#30]
In the https://github.com/alangarf/apple-one/blob/master/README.md it says in the Memory Map:

0xFF00 | 0xFFFF | 512B of block RAM for WozMon ROM

But should the first value not be 0xFE00, because otherwise it's just 256B? If it is actually 256B then the comment "512B of block RAM" should be changed.

**Comment by alangarf** [comment]
Thanks for the report, fixed.
