### ISSUE TITLE
Expanding RAM to 32KB

### ISSUE THREAD

**Issue by mobluse** [alangarf/apple-one#31]
According to the [ad](https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Apple_1_Advertisement_Oct_1976.jpg/330px-Apple_1_Advertisement_Oct_1976.jpg) Apple 1 could be expanded to 32KB RAM on-board using larger chips. Could you not expand the RAM to 32KB? I think it would be fun with more RAM. The iCE40HX8K-EVB has 512KB RAM.

**Comment by trcwm** [comment]
I don't have that board but geel free to send me one so I can implement it :)

**Comment by alangarf** [comment]
Closing issue as this is board specific and unless someone implements it and submits a PR this really isn't an issue. Thanks anyway.
