### ISSUE TITLE
No response on UART on ice40hx8k-evb

### ISSUE THREAD

**Issue by r4d10n** [alangarf/apple-one#33]
I tried loading the ice40hx8k-evb board files. The LEDs are blinking and I'm using just the UART for IO, without VGA/PS2. 

No response on UART with screen and miniterm (--rtscts /dev/ttyUSB1 115200). Even with CAPS entry. 

Tried setting the ps2_select to 1'b0. Still no luck. 

Anything else to check ? How do I check if CTS is willing ?

**Comment by alangarf** [comment]
By default there is a toggle pin that will switch between PS2 and UART input.
```
set_io button[2] F1
```
If you attach a button (or tap a jumper) to F1 and GND and press it, it should toggle between them.

Pin G1 much that same if you put a button will be the system reset.

It uses hardware CTS for the UART need to make sure the driver supports it. I have issues with MacOS drivers not supporting RTS/CTS.

If you reset it you should get an `@`
