### ISSUE TITLE
How to Use USB Serial on Upduino V2.0

### ISSUE THREAD

**Issue by Damianoux** [alangarf/apple-one#36]
To use the bultin USB FTDI serial port to access the woz monitor,  on Upduino V2.0,  just change rx,tx pin mapping in boards/upduino/yosys/ice40up5k.pcf as follows

set_io -nowarn uart_rx 15
set_io -nowarn uart_tx 14

Then in boards/upduino/yosys/Makefile, find the "prog:" target and remove -S switch. This allows iceprog to program the SPI flash onboard.
After programming the chip, on Linux the USB FTDI inteface may become unresponsive. To restore communication you can just unplug and reinsert USB connector, or  you can reload the ftdi kernel module, by issuing the command:
sudo rmmod ftdi_sio
followed by:
sudo mod_probe ftdi_sio

Damiano

**Comment by alangarf** [comment]
A PR is happily accepted to make this change.

Cheers!
